### ISSUE TITLE
Small width of caption

### ISSUE THREAD

**Issue by henrikt-ma** [otronarp/MCP033Examples#4]
In figure b014d, I'm surprised by the small width of the caption.  Is it intended to be that narrow, or is it an artifact or the figure export?

**Comment by otronarp** [comment]
All "line breaks" corresponds to explicitly specified paragraph breaks.

**Comment by henrikt-ma** [comment]
OK, in that case I must have missed one of the line breaks in the caption source (to be precise, it was the breaking of the second line that I failed to identify as a paragraph break).  My bad.  Looks good now.
